FROM nginx:latest
COPY /dist/spa/. /usr/share/nginx/html

# docker build -t harbor.cloud.netease.com/qztest/nsf-front-demo:v1.9.1 .
# docker push harbor.cloud.netease.com/qztest/nsf-front-demo:v1.9.1
# docker build -t harbor.cloud.netease.com/qztest/nsf-front-demo:v1.8.0_v2 .
# docker push harbor.cloud.netease.com/qztest/nsf-front-demo:v1.8.0_v2